random_state: 144
features:
  
  - ave_flot_air_flow
  - ave_flot_level
  - iron_feed
  - starch_flow
  - amina_flow
  - ore_pulp_flow
  - ore_pulp_pH
  - ore_pulp_density

cat_features:
  - 'Location'
  - 'WindGustDir'
  - 'WindDir9am'
  - 'WindDir3pm'
  - 'RainToday'


num_features:
  - 'MinTemp'
  - 'MaxTemp'
  - 'Rainfall'
  - 'Evaporation'
  - 'Sunshine'
  - 'WindGustSpeed'
  - 'WindSpeed9am'
  - 'WindSpeed3pm'
  - 'Humidity9am'
  - 'Humidity3pm'
  - 'Pressure9am'
  - 'Pressure3pm'
  - 'Cloud9am'
  - 'Cloud3pm'
  - 'Temp9am'
  - 'Temp3pm'
  - 'month'
  
  
  
test_size: 0.3
target: silica_concentrate

grid_params:
  - alpha
  - solver
  - tol

max_iter: 20000  

data: 
  train_path: data/train.csv
  test_path: data/test.csv

train:
  test_size: 0.2
  random_state: 42
  shuffle: true

model:
  name: HistGradientBoostingClassifier
  params:
     learning_rate: 0.01
     max_depth: 10


  store_path: ../models/


  
scorer:

  - f1_score
  - precision_score
  - recall_score