random_state: 144
directories:
    home:
    - 'C:/daten/numapathy/Dokumente/networksecurity_project/oct24_bmlops_int_weather/src'
    train:
    - 'data/train/train_data.csv'
    test:
    - 'data/test/test_data.csv'
    ref:
    - 'data/ref/ref_data.csv'
target:

  - 'RainTomorrow'


cat_features:
  - 'WindGustDir'
  - 'WindDir9am'
  - 'WindDir3pm'
  - 'RainToday'
  - 'Location'



num_features:
  - 'MinTemp'
  - 'MaxTemp'
  - 'Rainfall'
  - 'Evaporation'
  - 'Sunshine'
  - 'WindGustSpeed'
  - 'WindSpeed9am'
  - 'WindSpeed3pm'
  - 'Humidity9am'
  - 'Humidity3pm'
  - 'Pressure9am'
  - 'Pressure3pm'
  - 'Cloud9am'
  - 'Cloud3pm'
  - 'Temp9am'
  - 'Temp3pm'

   

grid_params:
  - alpha
  - solver
  - tol

max_iter: 20000  

data: 
  train_path: data/train/train_data.csv
  test_path: data/test/test_data.csv
  ref_path: data/ref/ref_data.csv


model:
  model_name: HistGradientBoostingClassifier
  mlflow_name: weather_forecast_model
  challenger_name : AdaBoostClassifier

  params:
     learning_rate: 0.01
     max_depth: 10


  store_path: steps/model.pkl


  
scorer:

  - f1_score
  - precision_score
  - recall_score

train_test_ratio:
  - 0.3