random_state: 144
target:

  - 'RainTomorrow'
  


cat_features:
  - 'WindGustDir'
  - 'WindDir9am'
  - 'WindDir3pm'
  - 'RainToday'
  - 'month'


num_features:
  - 'MinTemp'
  - 'MaxTemp'
  - 'Rainfall'
  - 'Evaporation'
  - 'Sunshine'
  - 'WindGustSpeed'
  - 'WindSpeed9am'
  - 'WindSpeed3pm'
  - 'Humidity9am'
  - 'Humidity3pm'
  - 'Pressure9am'
  - 'Pressure3pm'
  - 'Cloud9am'
  - 'Cloud3pm'
  - 'Temp9am'
  - 'Temp3pm'

  
  
  

grid_params:
  - alpha
  - solver
  - tol

max_iter: 20000  

data: 
  train_path: data/train.csv
  test_path: data/test.csv


model:
  name: HistGradientBoostingClassifier
  params:
     learning_rate: 0.01
     max_depth: 10


  store_path: ../models/


  
scorer:

  - f1_score
  - precision_score
  - recall_score