# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  #pull_request:
    branches: [ "master" ]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest ruff
        if [ -f requirements_full.txt ]; then pip install -r requirements_full.txt; fi

    # Install Ruff

    - name: Code checking with ruff
      run: |

        ruff check ./src
        ruff fix .

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'style fixes by ruff'


    - name: Retrain model
      run: |
        
        src/steps/retraining.py
        
   
